# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a41e4918aabfcb4b9ad3882e94ecee9c52fe1d8a28df9323c6234ebe18f7b844ffe2e9c7ea00cc8eaeaec0cde2f62fc71251e4adf2d5bf7ce74630d4710aa680

test:
  secret_key_base: 4b1aff8115b35f6ef6ae57ec7febad385e7e48c341c263f2032e850acbeff6478ed38079dc1a8443f5800296f59822666f8f3b17e1260318acfdc77e8b0677f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
