source 'https://rubygems.org'
ruby '2.0.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.2'

group :development do
gem 'sqlite3', '1.3.8'
end

gem 'sass-rails', '4.0.5'
gem 'uglifier', '2.1.1'
gem 'coffee-rails', '4.0.1'
gem 'jquery-rails', '3.0.4'
gem 'turbolinks', '1.1.1'
gem 'jbuilder', '1.0.2'

group :doc do
gem 'sdoc', '0.3.20', require: false
end

group :production do
# gem 'pg', '0.15.1'
gem 'rails_12factor', '0.0.2'
end

# Use mysql as the database for Active Record
gem 'mysql2', '~> 0.3.20'

# (Railsの開発効率を上げる - quiet_assetsを使って開発環境のログ(development.log)のログ内容を見やすくする - Rails Webook)[http://ruby-rails.hatenadiary.com/entry/20141029/1414584929]
group :development do
  gem 'quiet_assets'
end

group :development, :test do
  gem 'better_errors'     # 開発中のエラー画面をリッチにする
  gem 'binding_of_caller' # 開発中のエラー画面にさらに変数の値を表示する
  gem 'hirb'         # モデルの出力結果を表形式で表示するGem
  gem 'hirb-unicode' # 日本語などマルチバイト文字の出力時の出力結果のずれに対応
  gem 'pry-rails'  # rails console(もしくは、rails c)でirbの代わりにpryを使われる
  gem 'pry-doc'    # methodを表示
  gem 'pry-byebug' # デバッグを実施
  gem 'rails-erd'
  # 上記でうまくいかない、かつ、OSX Mavericksを使っている場合はこちらを使ってください
  #   # gem 'rails-erd', github: 'paulwittmann/rails-erd', branch: 'mavericks'
  #
end

